import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    always-on-top: true;
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        visible: true;
        alignment: LayoutAlignment.stretch;
        Text {
            font-italic: false;
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}