name: economyPlugin
version: '1.0-SNAPSHOT'
main: me.Mini.economyPlugin.EconomyPlugin
api-version: '1.19'

commands:
  eco:
    description: Manage player balances
    usage: /eco <set|give|remove> <player> <amount>
  balance:
    description: Check player balance
    usage: /balance [player]
    aliases: bal
  pay:
    description: Betal